# The main config file for your Jekyll template

# Site settings
title: Vitor Casadei
desc: Masters Student on Software Engineering at Federal University of São Carlos (UFSCar) campus Sorocaba. My area of interest is Accessibility on mobile, Universal Design, Interface Design Patterns and Accessibility Barriers.

url: https://ux-leris.github.io/vitor_casadei/
baseurl: '/vitor_casadei' # the subpath of your site, e.g. /blog
permalink: /:title/

# Meta settings
email: vitor.casadei@gmail.com
author: Vitor Casadei
personal_website: casadei.io
github_username: vcasadei
github_source: https://ux-leris.github.io/vitor_casadei/

# Optional settings
google_analytics: 'UA-XXXXXXXX-X'

# Pagination settings
paginate: 5
paginate_path: "/articles/page:num/"

# Navigation settings
navigation:
  - title: Home
    url: /
    desc: Home Page
  - title: Publications
    url: /publications/
    desc: A list of my publications
  - title: Articles
    url: /articles/
    desc: Some ideas I would like to share
  - title: Lattes
    url: http://lattes.cnpq.br/2959168271554057
    desc: Lattes


# Front Matter settings
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

# Build settings
include:
  - _pages
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate
